service: nyt-book-pipeline
frameworkVersion: '3'
package:
  individually: true
  patterns:
    - '!todo.txt'
    - '!framework'
    - '!functions'
    - '!node_modules'
    - '!test'
    - '!env.yml'
    - '!package-lock.json'
    - '!requirements.txt'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    STAGE: ${opt:stage, 'dev'}
    NYT_API_KEY: ${file(./env.yml):NYT_API_KEY}
    GOOGLE_API_KEY: ${file(./env.yml):GOOGLE_API_KEY}

functions:
  extract_data:
    handler: functions/extract/extract_data.index
    package: 
      patterns:
        - functions/extract/*
    layers:
      - {Ref: ApiBaseModuleLambdaLayer}
      - arn:aws:lambda:us-east-1:264456249408:layer:requestsLayer:5

layers:
  ApiBaseModule:
    path: ./functions/framework/base
    name: api-base-module
    description: 'framework classes'



